### ISSUE TITLE
Ability to set multiple destinations per gateway

### ISSUE THREAD

**Issue by v-ctiutiu** [digitalocean/k8s-staticroute-operator#10]
## Background

Currently, the operator supports a single entry in the destination field per gateway within the StaticRoute CRD. This is fine for simple use cases, but leads to multiple CRs if a setup requires multiple destinations per gateway. Dealing with multiple CRDs in this case can be hard to manage.

## Proposal

Change the `destination` filed in the StaticRoute CRD `spec` to array type. Creating a static routes resource with multiple destinations per gateway becomes:

```yaml
apiVersion: networking.digitalocean.com/v1
kind: StaticRoute
metadata:
  name: public-egress
spec:
  destinations: 
   - "34.160.111.145"
   - "34.117.59.81"
   - "32.17.9.81"
  gateway: "10.116.0.4"
```
